import './app.css';
import { useCatImage } from './hooks/useCatImage.ts';
import { useCatFact } from './hooks/useCatFact.ts';

const CAT_PREFIX_IMAGE_URL = 'https://cataas.com'

export function App() {
	const { fact, refreshRandomFact } = useCatFact();
	const { imageUrl  } = useCatImage({ fact });

	function handleGetNewFact() {
		refreshRandomFact();
	}


	return (
		<>
			<main>
				<h1>Cat's APP</h1>
				<button onClick={handleGetNewFact}>Get new fact</button>
				{ fact ? <p> {fact} </p> : <span> Loading... </span> }
				{ imageUrl ? <img src={`${CAT_PREFIX_IMAGE_URL}${imageUrl}`} alt={`image generated by first word: ${fact}`} /> : <p> Loading... </p> }
			</main>
		</>
	)
}